{% set name = "litedram" %}
{% set version = "2024.04" %}
{% set sha256 = "a2a22c21321fbb806f5b844f35e3d20467bef46783297b2864060f4b74be7318" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/enjoy-digital/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  entry_points:
    - litedram_gen = litedram.gen:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - litex >=2024.04
    - packaging
    - pyyaml

test:
  imports:
    - litedram
  commands:
    - litedram_gen --help

about:
  home: https://github.com/enjoy-digital/litedram
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Small footprint and configurable DRAM core
  description: Small footprint and configurable DRAM core
  dev_url: https://github.com/enjoy-digital/litedram

extra:
  recipe-maintainers:
    - enjoy-digital
    - timkpaine
